# Generated by Django 2.2.5 on 2019-09-24 19:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='current_room_csv',
            field=models.CharField(default='1,1', max_length=10),
        ),
        migrations.AddField(
            model_name='player',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
