# Generated by Django 2.2.5 on 2019-09-25 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190924_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='origin',
            field=models.CharField(default='', max_length=200),
        ),
    ]
